name: CI

on:
  push:
    branches: [default]
    tags:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install
        run: pip install .

      - uses: jakebailey/pyright-action@v2
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: build
        run: |
          pipx run build
          pipx run twine check --strict dist/*

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dist
          path: dist

  pypi-publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - python
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  check:
    if: always()

    needs:
      - build
      - typecheck

    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
